-- 1. GLOBAL SITUATION
-- Instructions:
--
-- Answering these questions will help you add information into the template.
-- Use these questions as guides to write SQL queries.
-- Use the output from the query to answer these questions.
-- a. What was the total forest area (in sq km) of the world in 1990? Please keep in mind that you can use the country record denoted as “World" in the region table.
--
-- b. What was the total forest area (in sq km) of the world in 2016? Please keep in mind that you can use the country record in the table is denoted as “World.”
--
-- c. What was the change (in sq km) in the forest area of the world from 1990 to 2016?
--
-- d. What was the percent change in forest area of the world between 1990 and 2016?
--
-- e. If you compare the amount of forest area lost between 1990 and 2016, to which country's total area in 2016 is it closest to?